config/routes.rb
Rails.application.routes.draw do
  resources :travels
  resources :users
  get 'login', to: 'login#index'
  get 'about', to: 'about#index'
  root 'login#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/travel.rb
class Travel < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :travel
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  @url_base = 'https://ulpool.herokuapp.com'
end

app/controllers/helpers/application_helper.rb
module ApplicationHelper
end

app/controllers/helpers/login_helper.rb
module LoginHelper
end

app/controllers/helpers/users_helper.rb
module UsersHelper
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    @users = User.all
    @url_base = 'https://ulpool.herokuapp.com'
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  before_action :set_travel, only: [:show, :edit, :update, :destroy]

  # GET /travels
  # GET /travels.json
  def index
    @travels = Travel.all
    @url_base = 'https://ulpool.herokuapp.com'
  end

  # GET /travels/1
  # GET /travels/1.json
  def show
  end

  # GET /travels/new
  def new
    @travel = Travel.new
  end

  # GET /travels/1/edit
  def edit
  end

  # POST /travels
  # POST /travels.json
  def create
    @travel = Travel.new(travel_params)

    respond_to do |format|
      if @travel.save
        format.html { redirect_to @travel, notice: 'Travel was successfully created.' }
        format.json { render :show, status: :created, location: @travel }
      else
        format.html { render :new }
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /travels/1
  # PATCH/PUT /travels/1.json
  def update
    respond_to do |format|
      if @travel.update(travel_params)
        format.html { redirect_to @travel, notice: 'Travel was successfully updated.' }
        format.json { render :show, status: :ok, location: @travel }
      else
        format.html { render :edit }
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travels/1
  # DELETE /travels/1.json
  def destroy
    @travel.destroy
    respond_to do |format|
      format.html { redirect_to travels_url, notice: 'Travel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_travel
      @travel = Travel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def travel_params
      params.require(:travel).permit(:user_id, :origen, :destino, :precio, :fecha, :hora, :asientos)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :name, :last_name, :gender, :cel, :birthdate, :has_a_car, :trademark, :model, :year, :color, :plate)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/about/index.html.erb
<div style="text-align: center; padding: 150px 0px">
  <h1>PÁGINA WEB CREADA POR:</h1>
  <br>
  <h2>ANGEL YARET HERRERA MEDINA</h2>
  <h2>AUGUSTO ALEXANDRE SEGURA HUAMAN</h2>
  <h2>CARLO STEPHANO DONAYRE MEDINA</h2>
  <h2>JOSE ENRIQUE SANDOVAL TIRADO</h2>
  <h2>JORGE RODRIGO CHAVEZ DIAZ</h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ULPool</title>

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>

  <body>
    <header>
      <nav class="be-red white large-padding font">
        <ul class="no-list row center-xs middle-xs">
          <li class="col-md">
            <h1 class="no-margin" id="logo">ULPooL</h1>
          </li>
          <li class="col-md">
            <%= link_to 'Inicio', root_path %>
          </li>
          <li class="col-md" onclick="window.location.href='/travels'">
            Lista de Viajes
          </li>
          <li class="col-md" onclick="verificarAdmin()">
            Usuarios Registrados
          </li>
          <li class="col-md" onclick="window.location.replace('<%= @url_base %>/about');">
            Acerca de
          </li>
          <li class="col-md" onclick="logout()">
            Logout
          </li>
        </ul>
      </nav>
    </header>
    <%= yield %>
    <script>
      function logout() {
        document.cookie = 'userid=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;';
        window.location.replace("<%= @url_base %>");
      }
      function verificarAdmin() {
        var userid = getCookie("userid")
        if (userid == 1) {
          window.location.replace("<%= @url_base %>/users");
        } else {
          alert("Logueate con un usuario admin para ingresar")
        }
      }
    </script>
  </body>
</html>

app/views/login/index.html.erb
<body>
  <link rel="stylesheet" type="text/css" href="/css/login.css" media="screen" />

  <!-- Button to open the modal login form -->
  <div class="first">
    <div id="titulo">Bienvenido a ULPool</div>
    <div id="espacio"></div>
    <div id="espacio"></div>
    <div id="espacio"></div>
    <div id="subtitulo">Escoja que acción va a realizar:</div>
    <div id="espacio"></div>
    <div id="espacio"></div>
    <button onclick="document.getElementById('id01').style.display='block'" style="width:200px;">Ingresar</button>
    <br>
    <button onclick="window.location.replace('<%= @url_base %>/users/new')" style="width:200px;">Crear nuevo usuario</button>
  </div>

  <!-- The Modal -->
  <div id="id01" class="modal">
    <span onclick="document.getElementById('id01').style.display='none'"
    class="close" title="Close Modal">&times;</span>

    <!-- Modal Content -->
    <form class="modal-content animate" action="/action_page.php">
      <div class="imgcontainer">
        <img src="/man.png" alt="Avatar" class="avatar">
      </div>

      <div class="container2">
        <label><b>Email</b></label>
        <input type="text" id="email" placeholder="Ingresa tu email" name="uname" required>

        <label><b>Contraseña</b></label>
        <input type="password" id="password" placeholder="Ingresa tu contraseña" name="psw" required>

        <button type="button" onclick="verificar()">Ingresar</button>
        <input type="checkbox" checked="checked"> Recordarme
      </div>

      <div class="container2" style="background-color:#f1f1f1">
        <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancelar</button>
        <span class="psw">Olvidaste tu <a href="#">contraseña?</a></span>
      </div>
    </form>
  </div>

  <script>
  function verificar() {
    var email = document.getElementById("email").value;
    var password = document.getElementById("password").value;
    var idGet = null
    var emailGet = null;
    var passwordGet = null;
    <% @users.each do |user| %>
    if(email == "<%= user.email %>") {
      idGet = "<%= user.id %>"
      emailGet = "<%= user.email %>"
      passwordGet = "<%= user.password%>"
    }
    <%end%>
    if (emailGet == null) {
      alert("Usuario no encontrado");
    } else {
      if(password == passwordGet ){
        setCookie("userid",idGet,5);
        window.location.replace("<%= @url_base %>/travels");
      } else {
        alert("Usuario y/o contraseña incorrectos");
      }
    }
  }
  </script>

  <script>
  // Get the modal
  var modal = document.getElementById('id01');

  // When the user clicks anywhere outside of the modal, close it
  window.onclick = function(event) {
    if (event.target == modal) {
      modal.style.display = "none";
    }
  }
  </script>
</body>

app/views/travels/_form.html.erb
<%= form_for(travel) do |f| %>
  <% if travel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(travel.errors.count, "error") %> prohibited this travel from being saved:</h2>

      <ul>
      <% travel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.select :user_id, options_for_select(User.all.map{|s|[s.email, s.id]}) %>
  </div>

  <div class="field">
    <%= f.label :origen %>
    <%= f.text_field :origen %>
  </div>

  <div class="field">
    <%= f.label :destino %>
    <%= f.text_field :destino %>
  </div>

  <div class="field">
    <%= f.label :precio %>
    <%= f.number_field :precio %>
  </div>

  <div class="field">
    <%= f.label :fecha %>
    <%= f.date_select :fecha %>
  </div>

  <div class="field">
    <%= f.label :hora %>
    <%= f.time_select :hora %>
  </div>

  <div class="field">
    <%= f.label :asientos %>
    <%= f.number_field :asientos %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/travels/edit.html.erb
<div style="padding: 0px 200px;">
<h1>Editar Viaje</h1>

<%= render 'form', travel: @travel %>

<%= link_to 'Show', @travel %> |
<%= link_to 'Back', travels_path %>
</div>

app/views/travels/index.html.erb
<link rel="stylesheet" type="text/css" href="/css/login.css" media="screen" />
<p id="notice"><%= notice %></p>

<h1>Lista de Viajes Disponibles</h1>

<table id="tablaViajes">
  <thead>
    <tr>
      <th>User</th>
      <th>Teléfono</th>
      <th>Origen</th>
      <th>Destino</th>
      <th>Precio</th>
      <th>Fecha</th>
      <th>Hora</th>
      <th>Asientos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @travels.each do |travel| %>
      <tr>
        <td><%= travel.user.email %></td>
        <td><%= travel.user.cel %></td>
        <td><%= travel.origen %></td>
        <td><%= travel.destino %></td>
        <td><%= travel.precio %></td>
        <td><%= travel.fecha %></td>
        <td><%= travel.hora.strftime("%H:%M") %></td>
        <td><%= travel.asientos %></td>
        <td><%= link_to 'Show', travel %></td>
        <td><button onclick="verificarEdicion('<%= travel.user.id %>','<%= travel.id %>')" style="width:100px;">Editar</button></td>
        <td data-iduser="<%= travel.user.id %>"><%= link_to 'Eliminar', travel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<script>
function verificarEdicion(userid, travelid) {
  getUserId = getCookie("userid");
  if (userid == getUserId) {
    window.location.replace("<%= @url_base %>/travels/" + travelid + "/edit");
  } else {
    alert("No puedes editar un viaje que no es tuyo")
  }

}

$(function () {
  $("#tablaViajes").on("click","a[data-method='delete']",function (event) {
    event.preventDefault();

    var id = getCookie("userid");

    if ($(this).parent().attr("data-iduser") != id) {
      alert("No puedes eliminar un viaje que no es tuyo");
      return false;
    }
  })
});
</script>

<%= link_to 'New Travel', new_travel_path %>

app/views/travels/new.html.erb
<div style="padding: 0px 200px;">
  <h1>Nuevo Viaje</h1>

  <%= render 'form', travel: @travel %>

  <%= link_to 'Back', travels_path %>
</div>

app/views/travels/show.html.erb
<div style="padding: 0px 200px;">
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @travel.user.email %>
</p>

<p>
  <strong>Origen:</strong>
  <%= @travel.origen %>
</p>

<p>
  <strong>Destino:</strong>
  <%= @travel.destino %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @travel.precio %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @travel.fecha %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @travel.hora.strftime("%H:%M") %>
</p>

<p>
  <strong>Asientos:</strong>
  <%= @travel.asientos %>
</p>

</div>
<div style="padding: 0px 230px;">
  <%= link_to 'Back', travels_path %>
</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.select :gender, [['Hombre', 'Hombre'], ['Mujer', 'Mujer']], class:"form-control"%>
  </div>

  <div class="field">
    <%= f.label :cel %>
    <%= f.number_field :cel %>
  </div>

  <div class="field">
    <%= f.label :birthdate %>
    <%= f.date_select :birthdate, start_year: 1910, end_year: Time.now.year %>
  </div>

  <div class="field">
    <%= f.label :has_a_car %>
    <%= f.check_box :has_a_car %>
  </div>

  <div class="field">
    <%= f.label :trademark %>
    <%= f.text_field :trademark %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.number_field :year %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="field">
    <%= f.label :plate %>
    <%= f.text_field :plate %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div style="padding: 0px 200px;">
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th>Password</th>
      <th>Name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Cel</th>
      <th>Birthdate</th>
      <th>Has a car</th>
      <th>Trademark</th>
      <th>Model</th>
      <th>Year</th>
      <th>Color</th>
      <th>Plate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.gender %></td>
        <td><%= user.cel %></td>
        <td><%= user.birthdate %></td>
        <td><%= user.has_a_car %></td>
        <td><%= user.trademark %></td>
        <td><%= user.model %></td>
        <td><%= user.year %></td>
        <td><%= user.color %></td>
        <td><%= user.plate %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div style="padding: 0px 200px;">
<h1>Usuario Nuevo</h1>

<%= render 'form', user: @user %>

</div>

app/views/users/show.html.erb
<div style="padding: 0px 200px;">
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Cel:</strong>
  <%= @user.cel %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @user.birthdate %>
</p>

<p>
  <strong>Has a car:</strong>
  <%= @user.has_a_car %>
</p>

<p>
  <strong>Trademark:</strong>
  <%= @user.trademark %>
</p>

<p>
  <strong>Model:</strong>
  <%= @user.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @user.year %>
</p>

<p>
  <strong>Color:</strong>
  <%= @user.color %>
</p>

<p>
  <strong>Plate:</strong>
  <%= @user.plate %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |

</div>